### ISSUE TITLE
Issue with Flet package

### ISSUE THREAD

**Issue by G-Pereira** [sparkmicro/Ki-nTree#154]
```
Traceback (most recent call last):
  File "/usr/bin/kintree", line 5, in <module>
    from kintree.kintree_gui import main
  File "/usr/lib/python3.11/site-packages/kintree/kintree_gui.py", line 3, in <module>
    from .gui.gui import kintree_gui
  File "/usr/lib/python3.11/site-packages/kintree/gui/gui.py", line 3, in <module>
    from .views.common import update_theme, handle_transition
  File "/usr/lib/python3.11/site-packages/kintree/gui/views/common.py", line 35, in <module>
    def handle_transition(page: ft.Page, transition: bool, update_page=False, timeout=0):
                                ^^^^^^^
AttributeError: module 'flet' has no attribute 'Page'
```

**Comment by G-Pereira** [comment]
This seems to happen on Flet package version 0.6.4 and works fine with Flet 0.5.2

**Comment by G-Pereira** [comment]
It is specific to Arch Linux and seems to be an issue with the [python-flet](https://aur.archlinux.org/packages/python-flet) package on Arch Linux, having Flet 0.6.2 on a python virtual environment works just fine
